# Generated by Django 4.1.5 on 2023-01-26 21:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artisan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=48)),
                ('last_name', models.CharField(max_length=48)),
                ('date_of_birth', models.DateField()),
                ('job_title', models.CharField(max_length=48)),
                ('company', models.CharField(max_length=48)),
                ('identifier', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=48)),
                ('official_name', models.CharField(max_length=128)),
                ('currency', models.CharField(max_length=48)),
                ('languages', models.CharField(max_length=256)),
                ('timezones', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='ArtisanInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_number', models.CharField(blank=True, max_length=48, null=True)),
                ('marital_status', models.CharField(blank=True, max_length=48, null=True)),
                ('number_of_children', models.IntegerField(blank=True, null=True)),
                ('working_hours', models.IntegerField(blank=True, null=True)),
                ('religion', models.CharField(blank=True, max_length=48, null=True)),
                ('artisan', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='artisanInfo', to='artisans.artisan')),
            ],
        ),
        migrations.AddField(
            model_name='artisan',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='artisan', to='artisans.country'),
        ),
    ]
